version: '3.8'

services:

  celery_beat:
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    command: celery -A tweet_tracker beat -l info
    env_file:
      - ./.env-prod
    depends_on:
      - redis

  celery_worker:
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    command: celery -A tweet_tracker worker -l info
    env_file:
      - ./.env-prod
    depends_on:
      - redis

  redis:
    image: redis:alpine

  nginx:
    build: ./nginx/
    ports:
      - '80:80'
    depends_on:
      - backend
      - frontend

  frontend:
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
      args:
        - NEXT_PUBLIC_PROD=true
    command: npm start
    expose:
      - '3000'
    depends_on:
      - backend

  backend:
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    command: gunicorn tweet_tracker.wsgi:application --bind 0.0.0.0:8000
    expose:
      - '8000'
    env_file:
      - ./.env-prod
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

volumes:
  postgres_data: